# Generated by Django 3.1.14 on 2024-02-26 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_scolarite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inscription',
            old_name='annee_scolaire',
            new_name='annee_scolaire_inscription',
        ),
    ]
