# Generated by Django 3.1.14 on 2024-02-28 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_scolarite', '0004_auto_20240228_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='Carte_de_retraite',
            field=models.BooleanField(default=False),
        ),
    ]
