# Generated by Django 3.1.14 on 2024-02-28 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_scolarite', '0005_auto_20240228_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscription',
            name='Boite_de_Craie',
        ),
        migrations.RemoveField(
            model_name='inscription',
            name='Carte_de_retraite',
        ),
        migrations.RemoveField(
            model_name='inscription',
            name='Marcarons',
        ),
        migrations.RemoveField(
            model_name='inscription',
            name='Ramette',
        ),
        migrations.RemoveField(
            model_name='inscription',
            name='Relevet_des_notes',
        ),
        migrations.RemoveField(
            model_name='inscription',
            name='Tricot',
        ),
        migrations.CreateModel(
            name='ArticlesInscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carte_de_retraite', models.BooleanField(default=False)),
                ('boite_de_craie', models.BooleanField(default=True)),
                ('macarons', models.BooleanField(default=True)),
                ('tricot', models.BooleanField(default=True)),
                ('releve_des_notes', models.BooleanField(default=True)),
                ('ramette', models.BooleanField(default=True)),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_scolarite.inscription')),
            ],
        ),
    ]
