# Generated by Django 3.1.14 on 2024-05-14 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_scolarite', '0006_auto_20240228_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versement',
            name='montant',
            field=models.BigIntegerField(default=0),
        ),
    ]
