# Generated by Django 3.1.14 on 2024-05-19 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_scolarite', '0007_auto_20240514_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='matricule',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
