# Generated by Django 3.1.14 on 2024-05-23 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_scolarite', '0009_auto_20240523_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlesinscription',
            name='inscription',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestion_scolarite.inscription'),
        ),
    ]
