# Generated by Django 3.2 on 2024-06-27 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_scolarite', '0011_auto_20240527_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anneescolaire',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='articlesinscription',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='classe',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='classe',
            name='nom',
            field=models.CharField(choices=[('Maternelle', 'Maternelle'), ('CP1', 'CP1'), ('CP2', 'CP2'), ('CE1', 'CE1'), ('CE2', 'CE2'), ('CM1', 'CM1'), ('CM2', 'CM2'), ('6 ème', '6 ème'), ('5 ème', '5 ème'), ('4 ème', '4 ème'), ('3 ème', '3 ème'), ('Seconde', 'Seconde'), ('Première', 'Première'), ('Terminale', 'Terminale')], max_length=255),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='scolarite',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='versement',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
